---
title: "Analisi Esplorativa"
output: markdowntemplates::minimal
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Corso di Laurea Triennale in Scienze Statistiche ed Economiche, Università degli Studi di Milano-Bicocca, A.A. 2021/22.

## Pagina WEB del corso.

Analisi Esplorativa (6 CFU) è una parte dell'insegnamento Analisi Statistica Multivariata (15 CFU). Si prega di leggere con attenzione tutte le informazioni presenti nel sito

* [Analisi Statistica Multivariata](https://aldosolari.github.io/ASM/) (15 CFU)


## Calendario delle lezioni.

|| Lezione || Data || Luogo || Orario ||
|-|-|-|-|-|-|-|-|-|-|
||  || ||  ||  || ||
|| 1 || 02-12-2021 || U6-30 || 12:30 - 15:30 (3 ore)  ||
|| 2 || 03-12-2021 || U9-01 || 13:30 - 16:30 (3 ore)  ||
||  || ||  ||  || ||
||  || ||  ||  || ||
|| 3 || 09-12-2021 || U6-30 || 12:30 - 15:30 (3 ore)  ||
|| 4 || 10-12-2021 || LAB905 || 13:30 - 16:30 (3 ore) ||
||  || ||  ||  || ||
||  || ||  ||  || ||
|| 5 || 14-12-2021 || U6-30 || 08:30 - 10:30 (2 ore) ||
|| 6 || 16-12-2021 || U6-30 || 12:30 - 15:30 (3 ore) ||
|| 7 || 17-12-2021 || U9-06 || 13:30 - 16:30 (3 ore) ||
||  || ||  ||  || ||
||  || ||  ||  || ||
|| 8 || 21-12-2021 || U6-30 || 08:30 - 10:30 (2 ore) ||
|| 9 || 23-12-2021 || U6-30 || 12:30 - 15:30 (3 ore) ||
||  || ||  ||  || ||
||  || ||  ||  || ||
|| 10 || 11-01-2022 || U6-30 ||08:30 - 10:30 (2 ore) ||
|| 11 || 13-01-2022 || U6-30 || 12:30 - 15:30 (3 ore) ||
|| 12 || 14-01-2022 || LAB905 || 13:30 - 16:30 (3 ore) ||
||  || ||  ||  || ||
||  || ||  ||  || ||
|| 13 || 18-01-2022 || U6-30 ||08:30 - 10:30 (2 ore) ||
|| 14 || 20-01-2022 || U6-30 || 12:30 - 14:30 (2 ore) ||
|| ~~15~~ || ~~21-01-2022~~ || ~~LAB905~~ || ~~13:30 - 16:30 (3 ore)~~ ||
||  || ||  ||  || ||
||  || ||  ||  || ||
|| 15 || 25-01-2022 || U6-30 ||08:30 - 10:30 (2 ore) ||
|| 16 || 28-01-2022 || LAB905 || 13:30 - 16:30 (3 ore) ||

Il calendario didattico potrà subire variazioni, si consiglia di consultare questa pagina regolarmente. 

## Tutorato.

Dott.ssa Chiara Gaia Magnani

|| Esercitazione || Data || Luogo || Orario ||
|-|-|-|-|-|-|-|-|-|-|
|| 1 || 27-01-2022 || U6-30 || 12:30 - 15:30 (3 ore) ||

[Esercizi simulazione esame](docs/esercizi/AE - Esercitazione sim esame.pdf).

[Esercizi vari](docs/esercizi/AE - Esercitazione esercizi vari.pdf).


## Materiale didattico.

<table>

<tr>
<td>**ARGOMENTI**</td>
<td>**MATERIALE**</td>
<td>**DIDATTICO**</td>
<td>**LIBRO DI TESTO**</td>
<td>**ESERCIZI**</td>
<td>**SOLUZIONI**</td>
</tr>

<tr>
<td>Introduzione al corso.</td>
<td> [SLIDES](docs/slides/1_multi.pdf). </td>
<td> </td>
<td>JW §1.1, 1.2 </td>
<td></td>
<td></td>
</tr>

<tr>
<td>La matrice dei dati.</td>
<td>[SLIDES](docs/slides/2_dati.pdf).</td>
<td>[R](docs/lab/2_dati.html). </td>
<td>JW §1.3, EH §1.3, §1.3.1</td>
<td>[ESERCIZI](docs/esercizi/2_dati_esercizi.pdf).</td>
<td>[SOLUZIONI](docs/esercizi/2_dati_soluzioni.pdf).</td>
</tr>

<tr>
<td>Rappresentazioni grafiche.</td>
<td>[SLIDES](docs/lab/3_rapgraf_slide.html).</td>
<td>[R](docs/lab/3_rapgraf.html). </td>
<td>JW §1.4, EH §2.2, 2.2.1, 2.2, 2.4</td>
<td></td>
<td></td>
</tr>

<tr>
<td>[Spazio delle variabili e delle osservazioni](docs/appunti/4_spaziBB.pdf).</td>
<td>[SLIDES](docs/slides/4_spazi.pdf).</td>
<td>[R](docs/lab/4_spazi.html). </td>
<td>JW §3.1, §3.2</td>
<td>[ESERCIZI](docs/esercizi/4_spazi_esercizi.pdf).</td>
<td>[SOLUZIONI](docs/esercizi/4_spazi_soluzioni.pdf).</td>
</tr>

<tr>
<td>[Dati centrati e standardizzati](docs/appunti/5_fmatrBB.pdf).</td>
<td>[SLIDES](docs/slides/5_fmatr.pdf).</td>
<td>[R](docs/lab/5_fmatr.html). </td>
<td>JW §3.5 </td>
<td>[ESERCIZI](docs/esercizi/5_fmatr_esercizi.pdf).</td>
<td>[SOLUZIONI](docs/esercizi/5_fmatr_soluzioni.pdf).</td>
</tr>


<tr>
<td>[Varianza totale e generalizzata](docs/appunti/6_varianzeBB.pdf).</td>
<td>[SLIDES](docs/slides/6_varianze.pdf).</td>
<td>[R](docs/lab/6_varianze.html). </td>
<td>JW §3.4 </td>
<td>[ESERCIZI](docs/esercizi/6_varianze_esercizi.pdf).</td>
<td>[SOLUZIONI](docs/esercizi/6_varianze_soluzioni.pdf).</td>
</tr>

<tr>
<td>[Teorema di decomposizione spettrale](docs/appunti/7_spectralBB.pdf).</td>
<td>[SLIDES](docs/slides/7_spectral.pdf).</td>
<td>[R](docs/lab/7_spectral.html). </td>
<td>JW §2A.14, §2A.15 </td>
<td>[ESERCIZI](docs/esercizi/7_spectral_esercizi.pdf).</td>
<td>[SOLUZIONI](docs/esercizi/7_spectral_soluzioni.pdf).</td>
</tr>

<tr>
<td>[Analisi delle componenti principali](docs/appunti/8_pcaBB.pdf).</td>
<td>[SLIDES](docs/slides/8_pca.pdf).</td>
<td>[R](docs/lab/8_pca.html). </td>
<td>JW §8.1, §8.2, §8A </td>
<td>[ESERCIZI](docs/esercizi/8_pca_esercizi.pdf).</td>
<td>[SOLUZIONI](docs/esercizi/8_pca_soluzioni.pdf).</td>
</tr>

<tr>
<td>PCA: applicazioni </td>
<td>[SLIDES](docs/slides/9_pca2.pdf).</td>
<td>[R](docs/lab/9_pca2.html)</td>
<td>JW §8.3 </td>
<td></td>
<td></td>
</tr>

<tr>
<td>[Analisi dei gruppi: metodo delle K-medie](docs/appunti/10_kmeansBB.pdf).</td>
<td>[SLIDES](docs/slides/10_kmeans.pdf).</td>
<td>[R](docs/lab/10_kmeans.html). </td>
<td>JW §12.1, EH §6.1, §6.2, §6.4 </td>
<td></td>
<td></td>
</tr>


<tr>
<td>[Distanze](docs/appunti/11_distBB.pdf).</td>
<td>[SLIDES](docs/slides/11_dist.pdf).</td>
<td>[R](docs/lab/11_dist.html). </td>
<td>JW §12.2, §12.4 </td>
<td></td>
<td></td>
</tr>


<tr>
<td>[Analisi dei gruppi: metodi gerarchici ](docs/appunti/12_hclustBB.pdf).</td>
<td>[SLIDES](docs/slides/12_hclust.pdf).</td>
<td>[R](docs/lab/12_hclust.html). </td>
<td>JW §12.3, EH §6.3 </td>
<td>[ESERCIZI](docs/esercizi/12_hclust_esercizi.pdf).</td>
<td>[SOLUZIONI](docs/esercizi/12_hclust_esercizi.pdf).</td>
</tr>

<tr>
<td>[Analisi fattoriale](docs/appunti/13_factBB.pdf).</td>
<td>[SLIDES](docs/slides/13_fact.pdf).</td>
<td>[R](docs/lab/14_fact.html). </td>
<td>JW §9.1, §9.2, §9.3, §9.4</td>
<td>[ESERCIZI](docs/esercizi/13_fact_esercizi.pdf).</td>
<td>[SOLUZIONI](docs/esercizi/13_fact_esercizi.pdf).</td>
</tr>

<tr>
<td>Analisi fattoriale: applicazioni.</td>
<td>[SLIDES](docs/slides/14_fact2.pdf).</td>
<td> </td>
<td>JW §9.5 </td>
<td></td>
<td></td>
</tr>

</table>


Il  materiale didattico potrà subire variazioni, si consiglia di consultare questa pagina regolarmente. 


I seguenti argomenti sono esclusi dal programma: *La dimostrazione relativa alla formula della correlazione tra punteggi componenti principali e variabili*; *Metodo di stima dei fattori principali*.


## Forum del corso. 

Seppure l'email sia il modo di mettersi in contatto con un
docente, gli studenti sono invitati a non porre domande
relative all’insegnamento (chiarimenti, soluzione di esercizi,
ecc..) tramite l‘utilizzo della posta elettronica, ma ad
utilizzare il forum presente nella pagina [MOODLE](https://elearning.unimib.it/) del corso
oppure richiedere un ricevimento.


## Propedeuticità.

Questa attività formativa deve essere preceduta dal superamento degli esami di Algebra lineare, Analisi Matematica I, Calcolo delle Probabilità e Statistica I. Si consiglia inoltre la conoscenza degli argomenti trattati nel modulo R per l'Analisi Statistica Multivariata.



## Calendario degli esami.

|| Sessione || Data || Luogo || Orario ||
|-|-|-|-|-|-|-|-|-|-|
||  || ||  ||  || ||
|| Invernale || 8 Febbraio 2022 || U7-11 || 14:30  ||
|| Invernale || 28 Febbraio 2022 || -  || 14:30 ||
|| Primaverile || - || - || - ||
|| Estiva || - || -  || - ||
|| Estiva || - || -  || - ||
|| Estiva || - || -  || - ||


## Modalità d'esame. 

* L'esame si svolgerà in laboratorio e sarà possibile utilizzare R o RStudio.

* La prova consiste in una serie di esercizi
    * Esercizi di teoria
    * Esercizi applicati (analisi dei dati)
    
* All’esame sarà possibile consultare sia la documentazione ufficiale di R che una selezione del codice utilizzato a lezione

* Codice R che verrà reso disponibile all'esame : [codice_AE](docs/lab/AE_code.pdf)

* I voti verranno pubblicati sui soliti canali. Nei giorni successivi alla pubblicazione del voto, verrà programmata una sessione per la visione compiti, unico momento nel quale ogni studente potrà chiedere chiarimenti sul proprio compito e voto corrispondente. 

* Per l'accettazione del voto vale la regola del silenzio-assenso. Lo studente può rifiutare il voto o richiedere l'orale non oltre alla data prevista per la visione dei compiti. L'orale può essere richiesto anche dal docente. La data della prova orale non potrà essere inferiore a tre giorni naturali successivi continui dalla data di pubblicazione del voto. L'orale si basa sul tutto il programma del corso di AE. 


## Simulazione prova d'esame.

[TESTO](docs/appelli/AE25012022_testo.pdf)

[SOLUZIONE]()

## Appelli passati.

Si riportano nel seguito il testo e le soluzioni di alcuni appelli passati a titolo esemplificativo ma non esaustivo. 

* [7 Febbraio 2020](docs/appelli/AE070220.pdf)
* [21 Febbraio 2020](docs/appelli/AE210220.pdf)
* [6 Febbraio 2019](docs/appelli/AE060219.pdf)
* [22 Febbraio 2019](docs/appelli/AE220219.pdf)
* [17 Aprile 2019](docs/appelli/AE170419.pdf)
* [3 Luglio 2019](docs/appelli/AE030719.pdf)
* [12 Febbraio 2018](docs/appelli/AE120218.pdf)



## Libri di testo.


* Johnson, Wichern (2007) Applied Multivariate Statistical Analysis (6th Edition), Pearson Prentice Hall

* Everitt, Hothorn (2011) An Introduction to Applied Multivariate Analysis with R, Springer

Tutti i libri di testo sono disponibili in formato elettronico presso la [biblioteca](https://www.biblio.unimib.it/it/risorse/accesso-alle-risorse-remoto).

